version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: notebook_app
    container_name: notebook_app
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    depends_on:
      - db

  webserver:
    image: nginx:stable
    container_name: notebook_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: notebook_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notebook
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
